"""Tests del analizador de diffs — MVP-7 Gate CI/CD.

Cubre DiffParser (sin LLM) y DiffAnalyzer (con mocks del LLM/RAG).
Los tests de integración del endpoint están en test_api_diff.py.
"""

from __future__ import annotations

from typing import Any
from unittest.mock import AsyncMock, MagicMock

import pytest

from rosetta.core.diff_analyzer import (
    DiffAnalyzer,
    DiffParser,
)
from rosetta.core.models import MarcoNormativo, Severidad

# ---------------------------------------------------------------------------
# Diffs de ejemplo
# ---------------------------------------------------------------------------

DIFF_SECRET_AWS = """\
diff --git a/config.py b/config.py
index abc1234..def5678 100644
--- a/config.py
+++ b/config.py
@@ -1,4 +1,7 @@
 import os
+
+AWS_ACCESS_KEY_ID = "AKIAIOSFODNN7EXAMPLE"
+AWS_SECRET_ACCESS_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
+AWS_DEFAULT_REGION = "us-east-1"

 def get_config():
"""

DIFF_NEUTRAL_COMMENT = """\
diff --git a/utils.py b/utils.py
index abc1234..def5678 100644
--- a/utils.py
+++ b/utils.py
@@ -10,6 +10,7 @@
 def format_date(dt):
+    # Formato ISO 8601 para compatibilidad con APIs externas
     return dt.isoformat()
"""

DIFF_LOCK_FILE = """\
diff --git a/package-lock.json b/package-lock.json
index abc1234..def5678 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -1,5 +1,6 @@
 {
+  "version": "2",
   "lockfileVersion": 1,
"""

DIFF_POETRY_LOCK = """\
diff --git a/poetry.lock b/poetry.lock
index abc..def 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -1,3 +1,4 @@
+# This file is automatically @generated by Poetry
 [[package]]
 name = "anthropic"
"""

DIFF_MULTI_ARCHIVO = """\
diff --git a/api/auth.py b/api/auth.py
index abc..def 100644
--- a/api/auth.py
+++ b/api/auth.py
@@ -5,6 +5,7 @@
 from fastapi import APIRouter
+SECRET_TOKEN = "hardcoded-secret-token-12345"

 router = APIRouter()
diff --git a/utils/helpers.py b/utils/helpers.py
index abc..def 100644
--- a/utils/helpers.py
+++ b/utils/helpers.py
@@ -1,4 +1,5 @@
 def greet(name):
+    # Helper para saludo
     return f"Hello {name}"
"""

DIFF_BINARY = """\
diff --git a/logo.png b/logo.png
index abc..def 100644
Binary files a/logo.png and b/logo.png differ
"""

DIFF_VACIO = ""

DIFF_SOLO_ELIMINACIONES = """\
diff --git a/old_config.py b/old_config.py
index abc..def 100644
--- a/old_config.py
+++ b/old_config.py
@@ -1,5 +1,2 @@
-SECRET = "old-secret"
-TOKEN = "old-token"
-DEBUG = True
 import os
"""


# ---------------------------------------------------------------------------
# Tests: DiffParser
# ---------------------------------------------------------------------------


class TestDiffParser:
    def test_parse_detecta_secret_aws(self) -> None:
        hunks = DiffParser.parse(DIFF_SECRET_AWS)
        assert len(hunks) == 1
        assert hunks[0].archivo == "config.py"
        assert hunks[0].linea_inicio == 1
        assert any("AKIAIOSFODNN7EXAMPLE" in line for line in hunks[0].lineas_anadidas)

    def test_parse_hunk_frozen(self) -> None:
        """DiffHunk debe ser inmutable (frozen=True)."""
        hunks = DiffParser.parse(DIFF_SECRET_AWS)
        with pytest.raises((AttributeError, TypeError)):
            hunks[0].archivo = "otro.py"  # type: ignore[misc]

    def test_parse_comentario_neutro(self) -> None:
        hunks = DiffParser.parse(DIFF_NEUTRAL_COMMENT)
        assert len(hunks) == 1
        assert hunks[0].archivo == "utils.py"
        assert any("ISO 8601" in line for line in hunks[0].lineas_anadidas)

    def test_parse_excluye_package_lock(self) -> None:
        hunks = DiffParser.parse(DIFF_LOCK_FILE)
        assert len(hunks) == 0

    def test_parse_excluye_poetry_lock(self) -> None:
        hunks = DiffParser.parse(DIFF_POETRY_LOCK)
        assert len(hunks) == 0

    def test_parse_excluye_binarios(self) -> None:
        hunks = DiffParser.parse(DIFF_BINARY)
        assert len(hunks) == 0

    def test_parse_diff_vacio(self) -> None:
        assert DiffParser.parse(DIFF_VACIO) == []

    def test_parse_solo_eliminaciones_no_genera_hunk(self) -> None:
        hunks = DiffParser.parse(DIFF_SOLO_ELIMINACIONES)
        assert len(hunks) == 0

    def test_parse_multi_archivo(self) -> None:
        hunks = DiffParser.parse(DIFF_MULTI_ARCHIVO)
        archivos = [h.archivo for h in hunks]
        assert "api/auth.py" in archivos
        assert "utils/helpers.py" in archivos

    def test_parse_exclude_paths_exacto(self) -> None:
        hunks = DiffParser.parse(DIFF_SECRET_AWS, exclude_paths=["config.py"])
        assert len(hunks) == 0

    def test_parse_exclude_paths_glob(self) -> None:
        hunks = DiffParser.parse(DIFF_SECRET_AWS, exclude_paths=["*.py"])
        assert len(hunks) == 0

    def test_parse_exclude_paths_directorio(self) -> None:
        hunks = DiffParser.parse(DIFF_MULTI_ARCHIVO, exclude_paths=["api/**"])
        archivos = [h.archivo for h in hunks]
        assert "api/auth.py" not in archivos
        assert "utils/helpers.py" in archivos

    def test_hunk_tiene_contenido(self) -> None:
        hunks = DiffParser.parse(DIFF_SECRET_AWS)
        assert hunks[0].tiene_contenido is True

    def test_hunk_contenido_anadido(self) -> None:
        hunks = DiffParser.parse(DIFF_SECRET_AWS)
        contenido = hunks[0].contenido_anadido
        assert "AKIAIOSFODNN7EXAMPLE" in contenido
        assert "wJalrXUtnFEMI" in contenido


# ---------------------------------------------------------------------------
# Helpers de mocks
# ---------------------------------------------------------------------------

_MARCOS = [MarcoNormativo.ISO_27001_2022]


def _make_llm_con_violacion(
    controles: list[str] | None = None,
    impacto: str = "alta",
) -> Any:
    """Mock LLM que responde con una violación."""
    tool_input = {
        "tiene_violacion": True,
        "controles_incumplidos": controles or ["A.8.24"],
        "cita_normativa": "A.8.24 Uso de la criptografía: Las claves deben gestionarse de forma segura.",
        "justificacion": "Se detectó una clave AWS hardcodeada en el código fuente.",
        "impacto_legal": impacto,
        "accion_mitigacion": "Eliminar la clave del código y usar variables de entorno o un secret manager.",
        "evidencia_auditoria": "Credencial expuesta en commit del PR.",
    }
    tool_call = MagicMock()
    tool_call.tool_input = tool_input
    response = MagicMock()
    response.tool_calls = [tool_call]
    llm = AsyncMock()
    llm.completar = AsyncMock(return_value=response)
    return llm


def _make_llm_sin_violacion() -> Any:
    """Mock LLM que responde sin violación."""
    tool_input = {
        "tiene_violacion": False,
        "controles_incumplidos": [],
        "cita_normativa": "",
        "justificacion": "El cambio es un comentario de código, normativamente neutro.",
        "impacto_legal": "informativa",
        "accion_mitigacion": "",
        "evidencia_auditoria": "",
    }
    tool_call = MagicMock()
    tool_call.tool_input = tool_input
    response = MagicMock()
    response.tool_calls = [tool_call]
    llm = AsyncMock()
    llm.completar = AsyncMock(return_value=response)
    return llm


def _make_llm_sin_tool_call() -> Any:
    """Mock LLM que no invoca ninguna tool (caso degenerado)."""
    response = MagicMock()
    response.tool_calls = []
    response.content = "No sé qué hacer."
    llm = AsyncMock()
    llm.completar = AsyncMock(return_value=response)
    return llm


def _make_rag() -> Any:
    rag = MagicMock()
    rag.recuperar.return_value = []
    return rag


# ---------------------------------------------------------------------------
# Tests: DiffAnalyzer
# ---------------------------------------------------------------------------


class TestDiffAnalyzer:
    @pytest.mark.asyncio
    async def test_secret_genera_violacion(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_con_violacion(), rag=_make_rag())
        result = await analyzer.analizar(DIFF_SECRET_AWS, marcos=_MARCOS)

        assert len(result.violaciones) == 1
        assert "A.8.24" in result.violaciones[0].controles_incumplidos

    @pytest.mark.asyncio
    async def test_secret_bloquea_con_umbral_alta(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_con_violacion(impacto="alta"), rag=_make_rag())
        result = await analyzer.analizar(
            DIFF_SECRET_AWS, marcos=_MARCOS, bloquear_si=Severidad.ALTA
        )
        assert result.bloquear is True

    @pytest.mark.asyncio
    async def test_impacto_bajo_no_bloquea_con_umbral_alta(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_con_violacion(impacto="baja"), rag=_make_rag())
        result = await analyzer.analizar(
            DIFF_NEUTRAL_COMMENT, marcos=_MARCOS, bloquear_si=Severidad.ALTA
        )
        assert result.bloquear is False

    @pytest.mark.asyncio
    async def test_impacto_critico_bloquea_con_cualquier_umbral(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_con_violacion(impacto="critica"), rag=_make_rag())
        result = await analyzer.analizar(
            DIFF_SECRET_AWS, marcos=_MARCOS, bloquear_si=Severidad.BAJA
        )
        assert result.bloquear is True

    @pytest.mark.asyncio
    async def test_comentario_neutro_no_viola(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_sin_violacion(), rag=_make_rag())
        result = await analyzer.analizar(DIFF_NEUTRAL_COMMENT, marcos=_MARCOS)

        assert len(result.violaciones) == 0
        assert result.bloquear is False

    @pytest.mark.asyncio
    async def test_diff_vacio_no_llama_llm(self) -> None:
        llm = _make_llm_con_violacion()
        analyzer = DiffAnalyzer(llm=llm, rag=_make_rag())
        result = await analyzer.analizar(DIFF_VACIO, marcos=_MARCOS)

        llm.completar.assert_not_called()
        assert result.total_hunks_analizados == 0
        assert len(result.violaciones) == 0

    @pytest.mark.asyncio
    async def test_exclude_paths_evita_llamada_llm(self) -> None:
        llm = _make_llm_con_violacion()
        analyzer = DiffAnalyzer(llm=llm, rag=_make_rag())
        result = await analyzer.analizar(
            DIFF_SECRET_AWS, marcos=_MARCOS, exclude_paths=["config.py"]
        )

        llm.completar.assert_not_called()
        assert len(result.violaciones) == 0

    @pytest.mark.asyncio
    async def test_sin_tool_call_no_genera_violacion(self) -> None:
        """Si el LLM no invoca la tool, se trata como sin violación (resiliente)."""
        analyzer = DiffAnalyzer(llm=_make_llm_sin_tool_call(), rag=_make_rag())
        result = await analyzer.analizar(DIFF_SECRET_AWS, marcos=_MARCOS)

        assert len(result.violaciones) == 0
        assert result.bloquear is False

    @pytest.mark.asyncio
    async def test_marcos_usados_en_resultado(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_sin_violacion(), rag=_make_rag())
        marcos = [MarcoNormativo.ISO_27001_2022, MarcoNormativo.ENS_2022]
        result = await analyzer.analizar(DIFF_NEUTRAL_COMMENT, marcos=marcos)

        assert MarcoNormativo.ISO_27001_2022 in result.marcos_usados
        assert MarcoNormativo.ENS_2022 in result.marcos_usados

    @pytest.mark.asyncio
    async def test_total_hunks_analizados_correcto(self) -> None:
        analyzer = DiffAnalyzer(llm=_make_llm_sin_violacion(), rag=_make_rag())
        result = await analyzer.analizar(DIFF_MULTI_ARCHIVO, marcos=_MARCOS)

        assert result.total_hunks_analizados == 2

    @pytest.mark.asyncio
    async def test_violacion_tiene_datos_correctos(self) -> None:
        analyzer = DiffAnalyzer(
            llm=_make_llm_con_violacion(controles=["A.8.24", "A.5.15"]), rag=_make_rag()
        )
        result = await analyzer.analizar(DIFF_SECRET_AWS, marcos=_MARCOS)

        assert len(result.violaciones) == 1
        v = result.violaciones[0]
        assert v.archivo == "config.py"
        assert "A.8.24" in v.controles_incumplidos
        assert "A.5.15" in v.controles_incumplidos
        assert v.impacto_legal == Severidad.ALTA
        assert len(v.lineas_afectadas) > 0

    @pytest.mark.asyncio
    async def test_impacto_invalido_cae_a_media(self) -> None:
        """Severidad desconocida del LLM debe caer a MEDIA sin romper."""
        analyzer = DiffAnalyzer(
            llm=_make_llm_con_violacion(impacto="super_critico"), rag=_make_rag()
        )
        result = await analyzer.analizar(DIFF_SECRET_AWS, marcos=_MARCOS)

        assert result.violaciones[0].impacto_legal == Severidad.MEDIA

    @pytest.mark.asyncio
    async def test_lock_file_no_genera_violacion(self) -> None:
        llm = _make_llm_con_violacion()
        analyzer = DiffAnalyzer(llm=llm, rag=_make_rag())
        result = await analyzer.analizar(DIFF_LOCK_FILE, marcos=_MARCOS)

        llm.completar.assert_not_called()
        assert len(result.violaciones) == 0
